# Override defaults for Prettier
printWidth: 100
# tabWidth: 2
# useTabs: false
# semi: true
singleQuote: true
# quoteProps: as-needed
# trailingComma: es5
# bracketSpacing: true
# arrowParens: always
# endOfLine: lf
overrides:
  - files:
      - 'webapp/**/*.js'
    options:
      singleQuote: false
